name: Build on push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    # Skip job if commit message contains "[skip ci]"
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
    steps:
      - name: Check out commit
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          npm install
          npm test
